[package]
name = "godot-tts"
version = "0.1.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
env_logger = "0.7"
gdnative = "0.9.0-preview.0"
tts = ">= 0.6.4"

[target.'cfg(windows)'.dependencies]
tolk = ">= 0.2.1"
