name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          sudo apt-get update
          sudo apt-get install -y libspeechd-dev
          rustup update
          cargo check --release

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      LIBCLANG_PATH: c:\program files\llvm\bin
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          choco install -qy llvm
          rustup update
          cargo check --release --all-features

  build_macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          rustup update
          cargo check --release

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          rustup update
          rustup target add aarch64-apple-ios x86_64-apple-ios
          cargo install cargo-lipo
          cargo lipo --release

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: |
          ./gradlew assemble
